# Generated by Django 3.1.5 on 2021-02-01 21:46

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 14, 46, 15, 431414)),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b338628-f93a-49f1-a352-2cecfb939392'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='strength',
            field=models.CharField(max_length=30),
        ),
    ]
