# Generated by Django 3.1.5 on 2021-02-01 21:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_auto_20210201_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.UUIDField(default=uuid.UUID('52f9b22b-2e0e-4d41-8957-f0bde17e3a16'), primary_key=True, serialize=False),
        ),
    ]
