# Generated by Django 3.1.5 on 2021-02-01 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_auto_20210201_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
