# Generated by Django 3.1.5 on 2021-02-02 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medications', '0005_auto_20210201_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='users_taking',
            field=models.ManyToManyField(default='null', null=True, related_name='medications_taking', to=settings.AUTH_USER_MODEL),
        ),
    ]
