# Generated by Django 3.1.5 on 2021-02-02 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medications', '0006_medication_users_taking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='users_taking',
            field=models.ManyToManyField(related_name='medications_taking', to=settings.AUTH_USER_MODEL),
        ),
    ]
