# Generated by Django 3.1.5 on 2021-02-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplog',
            name='dia',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bplog',
            name='pulse',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bplog',
            name='sys',
            field=models.IntegerField(default=1),
        ),
    ]
