# Generated by Django 3.1.5 on 2021-02-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp_logs', '0002_auto_20210206_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplog',
            name='notes',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
