# Generated by Django 3.1.5 on 2021-02-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp_logs', '0003_auto_20210206_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bplog',
            old_name='notes',
            new_name='log_notes',
        ),
    ]
