# Generated by Django 3.1.5 on 2021-02-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp_logs', '0005_auto_20210206_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bplog',
            old_name='log_note',
            new_name='note',
        ),
    ]
